version: '3.9'

services:
  postgres:
    image: postgres:15.5
    ports:
      - 5452:5452
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=musicapp
  distmusicapp_v0.2:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - '8089:8089'